// Generated by CoffeeScript 1.3.3
(function() {
  var LocalStrategy, User, passport;

  User = require('./models/user').Model;

  passport = require('passport');

  LocalStrategy = require('passport-local').Strategy;

  module.exports = function(app) {
    app.use(passport.initialize());
    app.use(passport.session());
    passport.serializeUser(function(user, done) {
      return done(null, user.username);
    });
    passport.deserializeUser(function(username, done) {
      return User.findOne(username, function(err, user) {
        return done(err, user);
      });
    });
    return passport.use('local', new LocalStrategy(function(username, password, done) {
      return User.findOne({
        'username': username
      }, function(err, user) {
        if (err) {
          return done(err);
        } else if (!user) {
          return done(null, false, {
            message: 'Uknown User'
          });
        } else {
          return user.validPassword(password, done);
        }
      });
    }));
  };

}).call(this);
