// Generated by CoffeeScript 1.4.0
(function() {
  var Requirement, RequirementUser, Schema, Work, mongoose, status;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  status = ['unstarted', 'design', 'development', 'testing', 'completed', 'discarded'];

  Work = new Schema({
    desc: String,
    date: Date,
    time: Number
  });

  RequirementUser = new Schema({
    username: String,
    commitment: {
      type: Number,
      "default": 0
    },
    work: [Work]
  });

  Requirement = new Schema({
    name: {
      type: String,
      unique: true
    },
    description: String,
    users: [RequirementUser],
    status: {
      type: String,
      "enum": status
    },
    estimation: {
      loc: Number,
      FP: Number,
      date: {
        start: Date,
        end: Date
      },
      time: Number
    },
    actual: {
      loc: Number,
      date: {
        start: Date,
        end: Date
      }
    }
  });

  Requirement.virtual('actual.time').get(function() {
    var task, time, user, _i, _j, _len, _len1, _ref, _ref1;
    time = 0;
    _ref = this.users;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      user = _ref[_i];
      _ref1 = user.work;
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        task = _ref1[_j];
        time += task.time;
      }
    }
    return time;
  });

  Requirement.virtual('actual.start').get(function() {
    var earliestDate, task, user, _i, _j, _len, _len1, _ref, _ref1;
    earliestDate = null;
    _ref = this.users;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      user = _ref[_i];
      _ref1 = user.work;
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        task = _ref1[_j];
        if (earliestDate) {
          if (task.date < earliestDate) {
            earliestDate = task.date;
          }
        } else {
          earliestDate = task.date;
        }
      }
    }
    return earliestDate;
  });

  exports.Model = mongoose.model('requirement', Requirement);

  exports.Schema = Requirement;

}).call(this);
