// Generated by CoffeeScript 1.4.0
(function() {
  var Requirement, RequirementUser, Schema, Work, mongoose;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  Work = new Schema({
    desc: String,
    date: Date,
    time: Number
  });

  RequirementUser = new Schema({
    username: String,
    commitment: Number,
    work: [Work]
  });

  Requirement = new Schema({
    name: String,
    description: String,
    users: [RequirementUser],
    estimation: {
      loc: Number,
      FP: Number,
      date: {
        start: Date,
        end: Date
      },
      time: Number
    },
    actual: {
      loc: Number,
      date: {
        start: Date,
        end: Date
      }
    }
  });

  Requirement.virtual('actual.time').get(function() {
    var task, time, user, _i, _j, _len, _len1, _ref, _ref1;
    time = 0;
    _ref = this.users;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      user = _ref[_i];
      _ref1 = user.work;
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        task = _ref1[_j];
        time += task.time;
      }
    }
    return time;
  });

  exports.Model = mongoose.model('requirement', Requirement);

  exports.Schema = Requirement;

}).call(this);
