// Generated by CoffeeScript 1.4.0
(function() {
  var Project, Schema, User, mongoose;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  Project = require('./project').Model;

  User = new Schema({
    username: {
      type: String,
      unique: true,
      required: true
    },
    password: String,
    projects: [String]
  });

  User.methods.validPassword = function(password, done) {
    if (this.password === password) {
      return done(null, this);
    } else {
      return done(null, false, {
        message: 'Invalid Password'
      });
    }
  };

  User.methods.getProjects = function(cb) {
    return Project.find({
      name: {
        $in: this.projects
      }
    }).exec(function(err, projects) {
      if (err) {
        return cb(err);
      } else {
        return cb(null, projects);
      }
    });
  };

  exports.Model = mongoose.model('user', User);

  exports.Schema = User;

}).call(this);
