// Generated by CoffeeScript 1.4.0
(function() {

  exports.user = function(req, res, next) {
    res.locals.user = req.user;
    res.locals.project = null;
    res.locals.requirement = null;
    return next();
  };

  exports.flash = function(req, res, next) {
    var messages;
    messages = req.session.messages || (req.session.messages = []);
    res.flash = function(type, text) {
      return messages.push({
        'type': type,
        'text': text
      });
    };
    res.locals.messages = messages;
    return next();
  };

}).call(this);
