// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = function(app) {
    require('./routes')(app);
    require('./routes/user')(app);
    return require('./routes/project')(app);
  };

}).call(this);
