// Generated by CoffeeScript 1.4.0
(function() {
  var Project;

  Project = require('./models/project').Model;

  module.exports = function(app) {
    require('./routes')(app);
    require('./routes/user')(app);
    require('./routes/project')(app);
    require('./routes/requirement')(app);
    app.param('project', function(req, res, next, name) {
      return Project.findOne({
        'name': name
      }).exec(function(err, project) {
        if (!err) {
          res.locals.project = req.project = project;
        }
        return next();
      });
    });
    return app.param('requirement', function(req, res, next, name) {
      var requirement, _i, _len, _ref;
      if (typeof res.locals.project !== 'undefined') {
        _ref = res.locals.project.requirements;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          requirement = _ref[_i];
          if (requirement.name = name) {
            res.locals.requirement = req.requirement = requirement;
          }
        }
      }
      return next();
    });
  };

}).call(this);
