// Generated by CoffeeScript 1.4.0
(function() {
  var passport, project, routes, user;

  routes = require('./routes');

  user = require('./routes/user');

  project = require('./routes/project');

  passport = require('passport');

  module.exports = function(app) {
    app.get('/', routes.index);
    app.get('/login', routes.login);
    app.post('/login', passport.authenticate('local', {
      successRedirect: '/',
      failureRedirect: '/login',
      failureFlash: true
    }));
    app.get('/register', routes.register);
    app.post('/register', routes.registerPost);
    app.get('/user', user.index);
    return app.get('/projects', project.index);
  };

}).call(this);
