// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = function(app) {
    return app.get('/404', function(req, res) {
      return res.render('error/404');
    });
  };

}).call(this);
