// Generated by CoffeeScript 1.4.0
(function() {
  var User, passport;

  User = require('../models/user').Model;

  passport = require('passport');

  module.exports = function(app) {
    app.get('/', function(req, res) {
      if (!req.user) {
        return res.redirect('/login');
      } else {
        return res.redirect('/user');
      }
    });
    app.get('/login', function(req, res) {
      return res.render('login');
    });
    app.post('/login', passport.authenticate('local', {
      successRedirect: '/',
      failureRedirect: '/login'
    }));
    app.get('/logout', function(req, res) {
      req.logOut();
      return res.redirect('/');
    });
    app.get('/register', function(req, res) {
      return res.render('register');
    });
    return app.post('/register', function(req, res) {
      var b, newUser;
      b = req.body;
      if (b.username && b.password) {
        if (b.password !== b.passwordConfirm) {
          res.flash('error', 'Passwords are not the same.');
          return res.redirect('/register');
        } else {
          newUser = new User();
          newUser.username = b.username;
          newUser.password = b.password;
          return newUser.save(function(err) {
            if (err) {
              res.flash('error', err);
              return res.redirect('/register');
            } else {
              res.flash('success', 'You have been successfully registered.');
              return res.redirect('/');
            }
          });
        }
      }
    });
  };

}).call(this);
