// Generated by CoffeeScript 1.4.0
(function() {
  var passport;

  passport = require('passport');

  module.exports = function(app) {
    app.get('/', function(req, res) {
      if (!req.user) {
        return res.redirect('/login');
      } else {
        return res.redirect('/projects');
      }
    });
    app.get('/login', function(req, res) {
      return res.render('login');
    });
    app.post('/login', passport.authenticate('local', {
      successRedirect: '/',
      failureRedirect: '/login'
    }));
    return app.get('/logout', function(req, res) {
      req.logOut();
      return res.redirect('/');
    });
  };

}).call(this);
