// Generated by CoffeeScript 1.4.0
(function() {
  var User;

  User = require('../models/user').Model;

  exports.index = function(req, res) {
    if (!req.user) {
      return res.redirect('/login');
    } else {
      return res.redirect('/users');
    }
  };

  exports.login = function(req, res) {
    return res.render('login');
  };

  exports.logout = function(req, res) {
    req.logOut();
    return req.redirect('/');
  };

  exports.register = function(req, res) {
    return res.render('register');
  };

  exports.registerPost = function(req, res) {
    var b, newUser;
    b = req.body;
    if (b.username && b.password) {
      if (b.password !== b.passwordConfirm) {
        return res.render('register', {
          message: 'Passwords are not the same.'
        });
      } else {
        newUser = new User();
        newUser.username = b.username;
        newUser.password = b.password;
        return newUser.save(function(err) {
          if (err) {
            return res.render('register', {
              message: err
            });
          } else {
            return res.render('index', {
              message: 'You have been successfully registered.'
            });
          }
        });
      }
    } else {
      return res.render('register', {
        message: 'username and password are required'
      });
    }
  };

}).call(this);
