// Generated by CoffeeScript 1.4.0
(function() {
  var Project;

  Project = require('../models/project').Model;

  module.exports = function(app) {
    app.get('/projects/:name', function(req, res) {
      Project.findOne({
        name: req.params.name
      }).exec;
      return function(err, project) {
        if (!err) {
          return res.render('project/index', {
            'project': project
          });
        } else {
          return res.redirect('/404');
        }
      };
    });
    app.get('/project/new', function(req, res) {
      return res.render('project/new');
    });
    return app.post('/project/new', function(req, res) {
      var b, newProject;
      if (!req.user) {
        res.flash('error', 'You must be logged in to create a new project.');
        return res.redirect('/login');
      }
      b = req.body;
      if (b.projectname) {
        newProject = new Project();
        newProject.name = b.projectname;
        return newProject.save(function(err) {
          if (!err) {
            req.user.projects.push(b.projectname);
            return req.user.save(function(err) {
              res.flash('success', 'Your project has been created.');
              return res.redirect('/user');
            });
          } else {
            Project.findOne({
              name: b.projectname
            }).exec;
            return function(err, prj) {
              if (prj) {
                res.flash('error', 'A project with that name already exists.');
                return res.redirect(req.originalUrl);
              }
            };
          }
        });
      } else {
        res.flash('error', 'Please provide project with a name.');
        return res.redirect(req.originalUrl);
      }
    });
  };

}).call(this);
