// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = function(app) {
    app.get('/projects/:project/requirements/new', function(req, res) {
      return res.render('requirement/new');
    });
    app.post('/projects/:project/requirements', function(req, res) {});
    app["delete"]('/projects/:project/requirements', function(req, res) {});
    app.get('/projects/:project/requirements/:requirement', function(req, res) {
      return res.render('requirement/index');
    });
    app.get('/projects/:project/requirements/:requirement/edit', function(req, res) {});
    app.post('/projects/:project/requirements/:requirement/users', function(req, res) {});
    app.get('/projects/:project/requirements/:requirement/users', function(req, res) {});
    app.get('/projects/:project/requirements/:requirement/user/:username', function(req, res) {});
    app.put('/projects/:project/requirements/:requirement/users/:username', function(req, res) {});
    app["delete"]('/projects/:project/requirements/:requirement/users', function(req, res) {});
    app.post('/projects/:project/requirements/:requirement/users/:username/work', function(req, res) {});
    app.get('/projects/:project/requirements/:requirement/users/:username/work', function(req, res) {});
    return app["delete"]('/projects/:project/requirements/:requirement/users/:username/work', function(req, res) {});
  };

}).call(this);
