// Generated by CoffeeScript 1.4.0
(function() {

  exports.index = function(req, res) {
    var u;
    if (!req.user) {
      return res.redirect('/login');
    }
    u = req.user;
    return u.getProjects(function(err, user_projects) {
      return req.render('user/index', {
        projects: user_projects,
        username: u.username
      });
    });
  };

}).call(this);
