// Generated by CoffeeScript 1.4.0
(function() {
  var User;

  User = require('../models/user').Model;

  module.exports = function(app) {
    app.get('/register', function(req, res) {
      return res.render('user/new');
    });
    app.post('/register', function(req, res) {
      var b, newUser;
      b = req.body;
      if (b.username && b.password) {
        if (b.password !== b.passwordConfirm) {
          res.flash('error', 'Passwords are not the same.');
          return res.redirect('/register');
        } else {
          newUser = new User();
          newUser.username = b.username;
          newUser.password = b.password;
          return newUser.save(function(err) {
            if (err) {
              res.flash('error', err);
              return res.redirect('/register');
            } else {
              res.flash('success', 'You have been successfully registered.');
              return res.redirect('/');
            }
          });
        }
      }
    });
    return app.get('/projects', function(req, res) {
      var u;
      if (!req.user) {
        return res.redirect('/login');
      }
      u = req.user;
      return u.getProjects(function(err, user_projects) {
        if (!err) {
          return res.render('user/index', {
            projects: user_projects,
            username: u.username
          });
        } else {
          return res.render('user/index');
        }
      });
    });
  };

}).call(this);
