// Generated by CoffeeScript 1.4.0
(function() {
  var passport;

  passport = require('passport');

  module.exports = function(app) {
    return app.get('/user', function(req, res) {
      var u;
      if (!req.user) {
        return res.redirect('/login');
      }
      u = req.user;
      return u.getProjects(function(err, user_projects) {
        console.log(user_projects);
        if (!err) {
          return res.render('user/index', {
            projects: user_projects,
            username: u.username
          });
        } else {
          return res.render('user/index');
        }
      });
    });
  };

}).call(this);
