// Generated by CoffeeScript 1.3.3
(function() {
  var Requirement, Schema, mongoose;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  Requirement = new Schema;

  exports.Model = mongoose.model('requirement', Requirement);

  exports.Schema = Requirement;

}).call(this);
